<?php
            $odpovede = "<option disabled selected value=\"-\">Vybrať</option>
                        <option>v žiadnom prípade to nechcem</option>
                        <option>nepáči sa mi to ale pre Madam/Pána to vydržim</option>
                        <option>nemám to rád, ale vzrušuje ma predstava, že som donútený/á</option>
                        <option>nevadí mi to</option>
                        <option>prečo by som to neskúsil/a</option>
                        <option>moja veľmi obľúbená praktika</option>
                        <option>vzrušuje ma to a chcel by som to stále</option>
                        <option>praktizujem to aj sám/a</option>
                        <option disabled >&nbsp;</option>"
;
   

$zoznamotazok = array(
    "Bitie" => [
        "otazkaA1"  =>  "Bičování kopřivami - tělo:",
        "otazkaA2"  =>  "Bičování kopřivami - obličej:",
        "otazkaA3"  =>  "Bičování kopřivami - zadek:",
        "otazkaA4"  =>  "Bičování kopřivami - pohlaví:",
        "otazkaA5"  =>  "Bičování kopřivami - prsa:",
        "otazkaA6"  =>  "Bití v pozici ohnutý přes koleno:",
        "otazkaA7"  =>  "Bití přes zadek:",
        "otazkaA8"  =>  "Bití přes přirození:",
        "otazkaA9"  =>  "Bití přes prsa:",
        "otazkaA10"  =>  "Bití po celém těle:",
        "otazkaA11"  =>  "Bití mírné: ",
        "otazkaA12"  =>  "Bití tvrdé:", 
        "otazkaA13"  =>  "Bití - rákoska:",
        "otazkaA14"  =>  "Bití - důtky:", 
        "otazkaA15"  =>  "Bití - bičík:",
        "otazkaA16"  =>  "Bití - řemen:",
        "otazkaA17"  =>  "Drsné zacházení:", 
        "otazkaA18"  =>  "Fackování přes tváře:",
        "otazkaA19"  =>  "Kousání:",
        "otazkaA20"  =>  "Bičování přes tělo:",
        "otazkaA21"  =>  "Bičování přes zadek:",
        "otazkaA22"  =>  "Bičování přes přirození:",
        "otazkaA23"  =>  "Bičování přes prsa:",
        "otazkaA24"  =>  "Poškrábání:",
        "otazkaA25"  =>  "Spanking, výprasky:",],
    
    "O t r o c t v í   a   s l u ž b a" => [
        "OtazkaB1" => "Líbání a uctívání bot Pána/Paní:",
        "OtazkaB2" => "Líbání a uctívání nohou Pána/Paní:",
        "OtazkaB3" => "Líbání a uctívání zadku Pána/Paní:",
        "OtazkaB4" => "Líbání a uctívání přirození Pána/Paní:",
        "OtazkaB5" => "Jíst jen Pánem/Paní povolené jídlo:",
        "OtazkaB6" => "Masturbace rukou před Pánem/Paní: ",
        "OtazkaB7" => "Nucená masturbace:",
        "OtazkaB8" => "Slízávání Pánova semene:",
        "OtazkaB9" => "Slízávání poševního sekretu Paní:",
        "OtazkaB10" => "Nucená nahota - v soukromí: ",
        "OtazkaB11" => "Nucená nahota - málo navštěvovaná veřejná prostranství (les, …):",
        "OtazkaB12" => "Nucená nahota - na veřejnosti (kde tě neznají): ",
        "OtazkaB13" => "Sloužit jako toaleta Pána/Paní - piss na tělo:",
        "OtazkaB14" => "Sloužit jako toaleta Pána/Paní - piss do úst:",
        "OtazkaB15" => "Sloužit jako toaleta Pána/Paní - scat na tělo:",
        "OtazkaB16" => "Sloužit jako toaleta Pána/Paní - scat do úst:",
        "OtazkaB17" => "Sloužit jako plivátko:",
        "OtazkaB18" => "Sloužit jako nábytek (stolička, podnožka, …):",
        "OtazkaB19" => "Masáž Pána/Paní:",
        "OtazkaB20" => "Ovládání tahem za vlasy:",
        "OtazkaB21" => "Facesitting - Pán/Paní sedí na obličeji: ",
        "OtazkaB22" => "Poslušnost, plnění rozkazů:",
        "OtazkaB23" => "Psychické ponižování v soukromí: ",
        "OtazkaB24" => "Psychické ponižování na veřejnosti:",
        "OtazkaB25" => "Nošení obojku - v soukromí:",
        "OtazkaB26" => "Nošení obojku - málo navštěvovaná veřejná prostranství (les, …):",
        "OtazkaB27" => "Nošení obojku - na veřejnosti skrytě:",
        "OtazkaB28" => "Nošení obojku - na veřejnosti neskrytě:",
        "OtazkaB29" => "Podřízené postavení: ",
        "OtazkaB30" => "Tresty za neposlušnost:",
        "OtazkaB31" => "Vulgární slova: ",
        "OtazkaB32" => "Vykonávání domácích prací na příkaz:",
        "OtazkaB33" => "Pás cudnosti:",
        "OtazkaB34" => "Odpírání orgasmu:",
        "OtazkaB35" => "Řízené orgasmy:",
        "OtazkaB36" => "Chození na WC na malou jen se souhlasem Pána/Paní: ",
        "OtazkaB37" => "Chození na WC na velkou jen se souhlasem Pána/Paní:",
        "OtazkaB38" => "Pomočení na příkaz:",
        "OtazkaB39" => "Pokálení na příkaz:",
        "OtazkaB40" => "Sex s Pánem/strap-on s Paní:",
        "OtazkaB41" => "Oholení ochlupení dle představ Pána/Paní:",
        "OtazkaB42" => "Nošení oblečení dle představ Pána/Paní:",
        "OtazkaB43" => "Nucené oblékání se (např. do ženských šatů) v soukromí:",
        "OtazkaB44" => "Omezení spánku:",
        "OtazkaB45" => "Zkoušky (fyzické): ",
        "OtazkaB46" => "Exhibicionismus (před cizími): ",
        "OtazkaB47" => "Být psem:",
        "OtazkaB48" => "Být pony: ",
        "OtazkaB49" => "Být služkou (všeobecně):",
        "OtazkaB50" => "Být služkou (sexuálně):",
        "OtazkaB51" => "Obléct se jako děvka - v soukromí: ",
        "OtazkaB52" => "Obléct se jako děvka - málo navštěvovaná veřejná prostranství (les, …):",
        "OtazkaB53" => "Obléct se jako děvka - na veřejnosti (kde tě neznají):",],
    
    "Mučenie a Tresty" => [
        "OtazkaC1" => "Mučení (všeobecné):",
        "OtazkaC2" => "Mučení přirození:",
        "OtazkaC3" => "Mučení bradavek:",
        "OtazkaC4" => "Kolíčky nebo svorky na bradavky:",
        "OtazkaC5" => "Kolíčky nebo svorky na přirození:",
        "OtazkaC6" => "Kolíčky nebo svorky na tělo: ",
        "OtazkaC7" => "Kolíčky nebo svorky na jazyk a uši:",
        "OtazkaC8" => "Závažíčka: ",
        "OtazkaC9" => "Zavěšování různých předmětů na přirození:",
        "OtazkaC10" => "Zavěšování různých předmětů na prsa:",
        "OtazkaC11" => "Stání či klečení v koutě:",
        "OtazkaC12" => "Ledové kostky na nebo do přirození:",
        "OtazkaC13" => "Ledové kostky do konečníku:",
        "OtazkaC14" => "Ledové kostky do úst: ",
        "OtazkaC15" => "Ledové kostky na bradavky:",
        "OtazkaC16" => "Ledové kostky na tělo:",
        "OtazkaC17" => "Být nahý/á ve sněhu: ",
        "OtazkaC18" => "Lechtání: ",
        "OtazkaC19" => "Mentolové a pálivé masti na pohlaví:",
        "OtazkaC20" => "Polykání vlastního semene:",
        "OtazkaC21" => "Polykání vlastního poševního sekretu:",
        "OtazkaC22" => "Horký vosk na nahé tělo: ",
        "OtazkaC23" => "Horký vosk na přirození:",
        "OtazkaC24" => "Horký vosk na zadek: ",
        "OtazkaC25" => "Horký vosk na prsa a bradavky: ",
        "OtazkaC26" => "Svíčka zastrčená v konečníku: ",
        "OtazkaC27" => "Svíčka zastrčená v přirození: ",
        "OtazkaC28" => "Horká voda na tělo:",
        "OtazkaC29" => "Horká voda na přirození:",
        "OtazkaC30" => "Ledová voda na tělo:",
        "OtazkaC31" => "Ledová voda na přirození:",
        "OtazkaC32" => "Ledová voda do konečníku: ",
        "OtazkaC33" => "Připínací penis - olizování a kouření: ",
        "OtazkaC34" => "Elektřina:",
        "OtazkaC35" => "Klystýry:",
        "OtazkaC36" => "Výslech:",
        "OtazkaC37" => "Zapichování jehel - tělo: ",
        "OtazkaC38" => "Zapichování jehel - přirození: ",
        "OtazkaC39" => "Zapichování jehel - prsa a bradavky:", ],
        
    "Obmädzovanie" => [
        "otazkaD1" => "Svazování mírné - možnost vlastního osvobození:",
        "otazkaD2" => "Svazování pevné - bez možnosti vlastního osvobození:",
        "otazkaD3" => "Svazování pevné - bez možnosti pohybu:",
        "otazkaD4" => "Nasazení roubíku:",
        "otazkaD5" => "Roubíky - látkové:",
        "otazkaD6" => "Roubíky - gumové:",
        "otazkaD7" => "Roubíky - páska:",
        "otazkaD8" => "Roubík ze spodního prádla (nošeného) - svého: ",
        "otazkaD9" => "Roubík ze spodního prádla (nošeného) - Pána/Paní:",
        "otazkaD10" => "Roubíky - kulička:",
        "otazkaD11" => "Roubíky - udidlo:",
        "otazkaD12" => "Roubíky - O kroužek:",
        "otazkaD13" => "Roubíky - penis:",
        "otazkaD14" => "Roubíky - postroje:",
        "otazkaD15" => "Roubíky - pony postroj:",
        "otazkaD16" => "Nošení roubíku - krátkodobé:",
        "otazkaD17" => "Nošení roubíku - dlouhodobé:",
        "otazkaD18" => "Omezení (pouta) - horní končetiny: ",
        "otazkaD19" => "Omezení (pouta) - dolní končetiny:",
        "otazkaD20" => "Omezení očního kontaktu (páska přes oči):",
        "otazkaD21" => "Omezení sluchu:",
        "otazkaD22" => "Svazování krátkodobé - minuty:",
        "otazkaD23" => "Svazování střednědobé - hodiny:",
        "otazkaD24" => "Svazování dlouhodobé - dny:",
        "otazkaD25" => "Svazování na veřejnosti viditelné:",
        "otazkaD26" => "Svazování na veřejnosti skryté (pod oblečením): ",
        "otazkaD27" => "Zavěšení svislé: ",
        "otazkaD28" => "Zavěšení hlavou dolů:",
        "otazkaD29" => "Zavěšení vodorovné:",
        "otazkaD30" => "Klec (být zavřen/a):",
        "otazkaD31" => "Cela (být zavřen/a):",
        "otazkaD32" => "Pouta - kožená:",
        "otazkaD33" => "Pouta - kovová (okovy a řetězy):",
        "otazkaD34" => "Pouta - provazy:",
        "otazkaD35" => "Pouta - šátky:",
        "otazkaD36" => "Pouta - lepící páska:",
        "otazkaD37" => "Kukla na hlavě: ",
        "otazkaD38" => "Rozpěrka: ",
        "otazkaD39" => "Být v kládě:",
        "otazkaD40" => "Ukřižování (provazy):",
        "otazkaD41" => "Podvazování genitálií:",
        "otazkaD42" => "Podvazování prsou:",
        "otazkaD43" => "Svěrací kazajka:",
        "otazkaD44" => "Mumifikace:",
        "otazkaD45" => "Svázaný v lese přes noc: ",],
    "Ďaľšie" => [
        "otazkaE1" => "Anální sex - přijímat:",
        "otazkaE2" => "Anální sex - poskytovat:",
        "otazkaE3" => "Anální kolíček malý:",
        "otazkaE4" => "Anální kolíček střední:",
        "otazkaE5" => "Anální kolíček velký:",
        "otazkaE6" => "Nošení análního kolíčku - krátkodobé:",
        "otazkaE7" => "Nošení análního kolíčku - dlouhodobé:",
        "otazkaE8" => "Anální kolíček veřejně nošený pod oblečením:",
        "otazkaE9" => "Připínací penis - orální sex:",
        "otazkaE10" => "Připínací penis - být znásilněn:",
        "otazkaE11" => "Nosit připínací penis:",
        "otazkaE12" => "Vibrátor v přirození:",
        "otazkaE13" => "Vibrátor v ústech:",
        "otazkaE14" => "Vibrátor v konečníku:",
        "otazkaE15" => "Orální sex - poskytovat:",
        "otazkaE16" => "Orální sex - přijímat:",
        "otazkaE17" => "Domácí práce:",
        "otazkaE18" => "Oblečení gumové/latex:",
        "otazkaE19" => "Kožené oblečení a doplňky:",
        "otazkaE20" => "Postroj kožený:",
        "otazkaE21" => "Postroj z provazů:", ],

    
    
    );
    ?>